name: remitchain-indexer
version: 0.1.0
specVersion: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'

schema:
  file: ./schema.graphql

network:
  chainId: '0x0adf44937998ec1f7a2e6aa148cc9915212ddb0d69d5a800d56931223b62a61b'
  endpoint: ['ws://127.0.0.1:9944']

dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleRemittanceSent
          kind: substrate/EventHandler
          filter:
            module: remitchain
            method: RemittanceSent
        - handler: handleCashOutRequested
          kind: substrate/EventHandler
          filter:
            module: remitchain
            method: CashOutRequested
        - handler: handleCashOutCompleted
          kind: substrate/EventHandler
          filter:
            module: remitchain
            method: CashOutCompleted
        - handler: handleDisputeOpened
          kind: substrate/EventHandler
          filter:
            module: remitchain
            method: DisputeOpened
